### ISSUE TITLE
parser doesn't seem to work in sandbox anymore

### ISSUE THREAD

**Issue by ssmlee** [linjunpop/receipt_verifier#6]
I see the latest response from apple store for a sandbox environment item purchase is as follows:

```
%{"receipt" => %{"bid" => "com.google.www", "bvrs" => "1",
    "is_in_intro_offer_period" => "false", "is_trial_period" => "false",
    "item_id" => "1322556240",
    "original_purchase_date" => "2017-12-22 18:16:14 Etc/GMT",
    "original_purchase_date_ms" => "1513262574202",
    "original_purchase_date_pst" => "2017-12-22 10:16:14 America/Los_Angeles",
    "original_transaction_id" => "1000020362025483",
    "product_id" => "com.google.001",
    "purchase_date" => "2017-12-22 18:16:14 Etc/GMT",
    "purchase_date_ms" => "1512966574202",
    "purchase_date_pst" => "2017-12-22 10:16:14 America/Los_Angeles",
    "quantity" => "1", "transaction_id" => "1000000362015483",
    "unique_identifier" => "0fcea4121732845ec3123dff859af528faaa75f85",
    "unique_vendor_identifier" => "AAAAAAAA-4D7A-DDAD-9126-922A7A34FD72"},
  "status" => 0}
```

And it seems the parser is not able to handle this. Wondering if there's something that I can do? Thanks.

**Comment by linjunpop** [comment]
Thanks for the information. I will fix it soon.

**Comment by linjunpop** [comment]
It seems Apple add something new:

> 2017-12-11 | Added receipt field for Subscription Introductory Offer Period.

**Comment by ssmlee** [comment]
Gotcha. Also it appears `environment` does not do anything for now? I tried to do 
```
ReceiptVerifier.verify(base64_receipt_ios, env: :production)
```

on a sandbox receipt and it still verifies. Is this the intended behavior? Thanks.

**Comment by linjunpop** [comment]
Currently

> If you send sandbox receipt to the production server, it will be auto resend to test server. Same for the production receipt

Maybe there should be a switch in this behavior.

**Comment by linjunpop** [comment]
@ssmlee Can you post the error messages on `parser is not able to handle this`

**Comment by ssmlee** [comment]
```
[error] 21:52:09.828  #PID<0.3124.0> running ArenaWeb.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /api/verify-receipt
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in ReceiptVerifier.Parser.parse_response/1
        (receipt_verifier) lib/receipt_verifier/parser.ex:12: ReceiptVerifier.Parser.parse_response(%{"receipt" => %{"bid" => "com.institute.iap-test", "bvrs" => "1", "is_in_intro_offer_period" => "false", "is_trial_period" => "false", "item_id" => "1328556240", "original_purchase_date" => "2017-12-22 18:16:14 Etc/GMT", "original_purchase_date_ms" => "1513966574202", "original_purchase_date_pst" => "2017-12-22 10:16:14 America/Los_Angeles", "original_transaction_id" => "1000001362025483", "product_id" => "com.iaptester.099", "purchase_date" => "2017-12-22 18:16:14 Etc/GMT", "purchase_date_ms" => "1513966574202", "purchase_date_pst" => "2017-12-22 10:16:14 America/Los_Angeles", "quantity" => "1", "transaction_id" => "1000000362025483", "unique_identifier" => "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "unique_vendor_identifier" => "AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAA"}, "status" => 0})
        (receipt_verifier) lib/receipt_verifier.ex:74: ReceiptVerifier.verify/2
```

something like this.

**Comment by linjunpop** [comment]
@ssmlee Sorry for late response, the receipt seems to be a *iOS 6 style transaction receipt*, which is currently not supported.

**Comment by ssmlee** [comment]
My iPhone is 5S and currently running iOS 8. I am curious if other iOS version & device would work..

**Comment by linjunpop** [comment]
I think it's not revalent to device. There are two types of receipts, one is *iOS 6 transaction receipt* receipt, and another one is *iOS 7 App receipt*. Which the *iOS 7 App receipt* is currently supported.

The data you pasted looks like an *iOS 6 transaction receipt*
