### ISSUE TITLE
Don't change the json_library

### ISSUE THREAD

**Issue by ercpereda** [linjunpop/receipt_verifier#9]
I change the json library in my config files

```elixir
# config/config.exs
......
config :receipt_verifier, :json_library, Poison
```
But I'm getting this error.

```
** (UndefinedFunctionError) function Jason.encode!/1 is undefined (module Jason is not available)
    Jason.encode!(%{"receipt-data" => "BASE64_ENCODED_RECEIPT_DATA"})
    (receipt_verifier) lib/receipt_verifier/client.ex:36: ReceiptVerifier.Client.do_request/2
    (receipt_verifier) lib/receipt_verifier/client.ex:19: ReceiptVerifier.Client.request/2
    (receipt_verifier) lib/receipt_verifier.ex:87: ReceiptVerifier.do_verify/2
```

**Comment by linjunpop** [comment]
I tried the same configuration:

```elixir
config :receipt_verifier, json_library: Poison
```

in IEx:

```elixir
Interactive Elixir (1.7.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Jason
Jason
iex(2)> Jason.encode!("foo")
** (UndefinedFunctionError) function Jason.encode!/1 is undefined (module Jason is not available)
    Jason.encode!("foo")
iex(2)> ReceiptVerifier.verify("foo")
{:error,
 %ReceiptVerifier.Error{
   code: 21002,
   message: "The data in the receipt-data property was malformed or missing.",
   meta: []
 }}
iex(5)> require ReceiptVerifier.JSON
ReceiptVerifier.JSON
iex(7)> ReceiptVerifier.JSON.encode!("{}")
"\"{}\""
iex(8)> Poison.encode!("{}")
"\"{}\""
iex(9)> Application.get_env(:receipt_verifier, :json_library)
Poison
iex(10)>
```

**Comment by ercpereda** [comment]
is correct the file where I put the configuration? `config/config.ex`

**Comment by linjunpop** [comment]
Please see this demo: https://github.com/linjunpop/receipt_verifier_demo

**Comment by ercpereda** [comment]
Sorry I was offline :-) Seems like the problem is with something in my config. Thanks for this library.
@linjunpop Do you have something similar for android?

**Comment by linjunpop** [comment]
No, you might want to search on hex.pm or craft one by yourself? Happy hacking.
